language: python
python:
    - "2.4"
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"

script: nosetests -vv

notifications:
    email:
        on_success: change
        on_failure: change
